version: '3'
services:
  node:
    container_name: ethereum-node
    image: ethereum/client-go
    ports:
      - "127.0.0.1:8545:8545"
      - "30303:30303"
    volumes:
      - ./data:/root
    command: >
      --cache=1024
      --syncmode "light"
      --rpc
      --rpcapi "db,eth,net,web3,personal,admin,miner"
      --rpccorsdomain="*"
      --rpcaddr "0.0.0.0"
